name: The Barbarian
favicon: null
layout_spectrum: 0.5991225533653051
typography_spectrum: 0.8766693626530468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.43384598987177014
  lightness: 0.7642072404269129
  saturation: 0.455976277589798
  rhythmicContrast: 0.027442745864391327
purpose: []
